### ISSUE TITLE
Why does the feature of "Ask a question" use a dialog instead of a Markdown cell?

### ISSUE THREAD

**Issue by MRYingLEE** [TiesdeKok/chat-gpt-jupyter-extension#19]
Maybe the selected Markdown cell can be used as the question input area.

Then the UI could be neater.

**Comment by TiesdeKok** [comment]
That functionality is already included through the complete button. You can create an empty cell, type your question, and click complete. This does make the question input box somewhat redundant; however, I wanted to add the functionality so that I can re-use it once I get around to adding the follow-up functionality.
