### ISSUE TITLE
Stuck on first page

### ISSUE THREAD

**Issue by rfacey** [TiesdeKok/chat-gpt-jupyter-extension#28]
Downloaded the extension. The "Which AI Provider do you want to use?" prompt has a loading circle under it that won't complete. The "What is your OpenAI API Key?" prompt allows me to type my API into the box, but won't save my API key after.

![image](https://user-images.githubusercontent.com/38757588/234918966-07f2e7f4-661b-4f47-93de-40305d305155.png)

**Comment by TiesdeKok** [comment]
Hi @rfacey ,

Sorry for the confusion, I have a fix in the works for this but that won't be available for a few days.

You should be able to solve this by opening up the regular chatgpt page, send a message there, and then come back to the settings page and refresh it. From that point on it should all work as expected.

The issue is that it doesn't prompt you to authenticate on the options page, only when you are using the extension. Instead it gets stuck on the spinning circle.

Ties

**Comment by rfacey** [comment]
That worked perfectly. Thank you!

**Comment by nourjaff22** [comment]
Hello 

Iam facing the same issue , What should I send to chatgpt in order to make it work ?
